language: node_js
node_js:
  - "11.6.0"

service:
  - postgresql

env:
  - DB_PASSWORD=''

before_script:
  - psql -c 'create database blogger;' -U postgres
  - chmod +x test.sh

script:
  - ./test.sh
