version: "3.7"
services:
  blogs:
    build: "./blog-apis"
    environment:
      DB_URL: db
      NODE_ENV: "production"
    depends_on:
      - db

  comments:
    build: "./comment-apis"
    environment:
      DB_URL: db
      NODE_ENV: "production"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p23p
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blogs
      - comments
